apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holiday-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "leetd.dev"
spec:
  # ingressClassName: azure-application-gateway
  rules:
  - host: leetd.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: holiday-web-service
            port:
              number: 8081
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: holiday-api-service
            port:
              number: 5000

