apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holiday-web-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway # must use annotation for use of ApplicationGateway | Listeners
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "leetd-dev" # uploaded cert 'leetd.dev', key vault cert 'leetd-dev'
    appgw.ingress.kubernetes.io/health-probe-path: "/" # for backend health check controller
spec:
  # ingressClassName: azure-application-gateway
  rules:
  - host: leetd.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: holiday-web-service
            port:
              number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holiday-api-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway # must use annotation for use of ApplicationGateway | Listeners
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "leetd-dev" # uploaded cert 'leetd.dev', key vault cert 'leetd-dev'
    appgw.ingress.kubernetes.io/health-probe-path: "/api/healthcheck" # for backend health check controller
spec:
  # ingressClassName: azure-application-gateway
  rules:
  - host: leetd.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: holiday-api-service
            port:
              number: 5000