apiVersion: v1
kind: Secret
metadata: 
  name: postgre-secret
  namespace: dev
type: Opaque
data: 
  db_user: cG9zdGdyZXMK
  db_password: Y3ByVndKbzd6bGlvaGdRd0V1bmtrRHZrT3RBdU9DVHZDbW5Samp3S2w2Y1BJRTBKMGhKOVZjbmtHV2RhU3g5Rwo=