controller:
  config:
    http-snippet: |
      proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=static:2m max_size=100m inactive=60m use_temp_path=off;
  
  kind: DaemonSet
  
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
  
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack #<PREFIX>-prometheus-stack
      namespace: "monitoring" # ns of prometheus-stack