apiVersion: v1
kind: Secret
metadata: 
  name: postgre-secret
  namespace: dev
type: Opaque
data: 
  db_user: cG9zdGdyZXMK
  db_password: dkFJMWZMWXdacTRpYWtSVWVNd3JsdFRoUmkwOVFmcDdCTVhEaVQxd2VyQVVQeERtMkVCMzVQZm11c0UxcnhQTAo=