apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-holiday-api-service  # Use release name for service name
  namespace: {{ .Namespace }}
spec:
  selector:
    app: holiday-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

# apiVersion: v1
# kind: Service
# metadata:
#   name: holiday-api-service
#   namespace: dev
# spec:
#   selector:
#     app: holiday-api
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000