version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: dotnet-7-dapper-crud-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
  webapi:
    container_name: api
    depends_on:
      - postgres
    image: leetd/holiday-api:v2
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      DbSettings__Server: postgres
      DbSettings__Database: dotnet-7-dapper-crud-api
      DbSettings__UserId: postgres
      DbSettings__Password: mysecretpassword
      Api__Protocol: http
      Api__Host: 0.0.0.0
      Api__Port: 5000
    ports:
      - 4001:5000
    networks:
      - frontend_network
      - backend_network
  web:
    image: leetd/holiday-web:v1
    container_name: web
    environment:
      API_URL: http://localhost:4001
    ports:
      - 8080:8080
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
volumes:
  postgres_data: