name: Trigger auto deployment for buffalocontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/buffalocontainerapp-AutoDeployTrigger-a6401916-73c7-4f9f-90c0-27146ba99744.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BUFFALOCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUFFALOCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUFFALOCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: buffaloacr.azurecr.io
          registryUsername: ${{ secrets.BUFFALOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUFFALOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: buffalocontainerapp
          resourceGroup: az104-rg
          imageToBuild: buffaloacr.azurecr.io/buffalocontainerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


